[theme]
primaryColor = "#10a37f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#202123"
textColor = "#353740"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
